<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MomiMpRelay</AssemblyName>
    <RootNamespace>MomiMpRelay</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteNetLib" Version="2.0.0" />
  </ItemGroup>

</Project>